name: Build Android APK

on:
  workflow_dispatch: # Erlaubt es uns, den Build manuell per Mausklick zu starten

jobs:
  build:
    runs-on: ubuntu-latest

    # Zwingt GitHub Actions jetzt schon auf das zukunftssichere Node 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Node.js einrichten
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Hier stand fälschlicherweise node-level. Korrigiert!

    - name: Cordova installieren
      run: npm install -g cordova

    - name: Cordova Projekt aufbauen
      run: |
        cordova create app de.linuxcore.vokabeltrainer Vokabeltrainer
        cd app
        rm -rf www/*
        cp ../index.html www/
        cp ../config.xml .
        cp ../book.png .
        cordova platform add android

    - name: Java einrichten
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Android SDK bereitstellen
      uses: android-actions/setup-android@v3

    - name: APK kompilieren
      run: |
        cd app
        cordova build android --debug

    - name: APK als Download bereitstellen
      uses: actions/upload-artifact@v4
      with:
        name: Vokabeltrainer-APK
        path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
